package Modelos;
// Generated Sep 29, 2018 5:52:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private int idCarrera;
     private Centrodetrabajo centrodetrabajo;
     private String nombreCarrera;
     private Integer duracion;
     private Set alumnos = new HashSet(0);

    public Carrera() {
    }

	
    public Carrera(int idCarrera) {
        this.idCarrera = idCarrera;
    }
    public Carrera(int idCarrera, Centrodetrabajo centrodetrabajo, String nombreCarrera, Integer duracion, Set alumnos) {
       this.idCarrera = idCarrera;
       this.centrodetrabajo = centrodetrabajo;
       this.nombreCarrera = nombreCarrera;
       this.duracion = duracion;
       this.alumnos = alumnos;
    }
   
    public int getIdCarrera() {
        return this.idCarrera;
    }
    
    public void setIdCarrera(int idCarrera) {
        this.idCarrera = idCarrera;
    }
    public Centrodetrabajo getCentrodetrabajo() {
        return this.centrodetrabajo;
    }
    
    public void setCentrodetrabajo(Centrodetrabajo centrodetrabajo) {
        this.centrodetrabajo = centrodetrabajo;
    }
    public String getNombreCarrera() {
        return this.nombreCarrera;
    }
    
    public void setNombreCarrera(String nombreCarrera) {
        this.nombreCarrera = nombreCarrera;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public Set getAlumnos() {
        return this.alumnos;
    }
    
    public void setAlumnos(Set alumnos) {
        this.alumnos = alumnos;
    }




}


