package Modelos;
// Generated Sep 29, 2018 5:52:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Centrodetrabajo generated by hbm2java
 */
public class Centrodetrabajo  implements java.io.Serializable {


     private int idCentroDeTrabajo;
     private String nombreCentroDeTrabajo;
     private Set carreras = new HashSet(0);

    public Centrodetrabajo() {
    }

	
    public Centrodetrabajo(int idCentroDeTrabajo) {
        this.idCentroDeTrabajo = idCentroDeTrabajo;
    }
    public Centrodetrabajo(int idCentroDeTrabajo, String nombreCentroDeTrabajo, Set carreras) {
       this.idCentroDeTrabajo = idCentroDeTrabajo;
       this.nombreCentroDeTrabajo = nombreCentroDeTrabajo;
       this.carreras = carreras;
    }
   
    public int getIdCentroDeTrabajo() {
        return this.idCentroDeTrabajo;
    }
    
    public void setIdCentroDeTrabajo(int idCentroDeTrabajo) {
        this.idCentroDeTrabajo = idCentroDeTrabajo;
    }
    public String getNombreCentroDeTrabajo() {
        return this.nombreCentroDeTrabajo;
    }
    
    public void setNombreCentroDeTrabajo(String nombreCentroDeTrabajo) {
        this.nombreCentroDeTrabajo = nombreCentroDeTrabajo;
    }
    public Set getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Set carreras) {
        this.carreras = carreras;
    }




}


