package Modelos;
// Generated Sep 29, 2018 5:52:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materias generated by hbm2java
 */
public class Materias  implements java.io.Serializable {


     private int idMaterias;
     private String nombreMateria;
     private Integer creditos;
     private Set examens = new HashSet(0);

    public Materias() {
    }

	
    public Materias(int idMaterias) {
        this.idMaterias = idMaterias;
    }
    public Materias(int idMaterias, String nombreMateria, Integer creditos, Set examens) {
       this.idMaterias = idMaterias;
       this.nombreMateria = nombreMateria;
       this.creditos = creditos;
       this.examens = examens;
    }
   
    public int getIdMaterias() {
        return this.idMaterias;
    }
    
    public void setIdMaterias(int idMaterias) {
        this.idMaterias = idMaterias;
    }
    public String getNombreMateria() {
        return this.nombreMateria;
    }
    
    public void setNombreMateria(String nombreMateria) {
        this.nombreMateria = nombreMateria;
    }
    public Integer getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Integer creditos) {
        this.creditos = creditos;
    }
    public Set getExamens() {
        return this.examens;
    }
    
    public void setExamens(Set examens) {
        this.examens = examens;
    }




}


