package ClienteRemoto;


/**
* ClienteRemoto/ClienteRem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClienteRemoto.idl
* Monday, September 24, 2018 6:21:16 PM CDT
*/

public interface ClienteRem extends ClienteRemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClienteRem
