package ClienteRemoto;


/**
* ClienteRemoto/ClienteRemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClienteRemoto.idl
* Monday, September 24, 2018 6:21:16 PM CDT
*/

public interface ClienteRemOperations 
{
  String Saludar (String nombre);
  double Suma (double x, double y);
  double Resta (double x, double y);
  double Division (double x, double y);
  double Multiplicacion (double x, double y);
} // interface ClienteRemOperations
