/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Interfaces.AlumnoInt;
import Interfaces.CarreraInt;
import Modelo.Alumno;
import Modelo.Carrera;
import Modelo.Centrodetrabajo;
import java.awt.Dimension;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.transaction.HeuristicMixedException;
import javax.transaction.HeuristicRollbackException;
import javax.transaction.RollbackException;
import javax.transaction.SystemException;
import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;

/**
 *
 * @author sam-y
 */
public class Consulta_Alumno extends javax.swing.JInternalFrame {

    String[][] datos;

    public Consulta_Alumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(162, 177, 192));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alumnos");

        jButton5.setText("Generar Reporte");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setText("Ok");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Matriculo", "Nombre", "A. Paterno", "A. Materno", "Fecha Nac.", "Calle", "Colonia", "Numero", "CP", "Sexo", "e-mail", "id de Carrera"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(9).setPreferredWidth(80);
            Tabla.getColumnModel().getColumn(11).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(0, 0, 0)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed


    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String stringInput = JOptionPane.showInputDialog("Ingrese un nombre para el reporte");
            if (stringInput != null && (Integer.valueOf(stringInput.charAt(0)) - 9) > 0) {
                String ruta = stringInput + ".xls";
                String[][] a = datos;
                WorkbookSettings conf = new WorkbookSettings();
                conf.setEncoding("ISO-8859-1");
                WritableWorkbook workbook = Workbook.createWorkbook(new File(ruta), conf);
                //crear hojas
                WritableSheet sheet = workbook.createSheet("Resultado", 0);

                WritableFont h = new WritableFont(WritableFont.ARIAL, 16, WritableFont.NO_BOLD);
                WritableCellFormat hformat = new WritableCellFormat(h);

                for (int i = 0; i < a.length; i++) {
                    for (int j = 0; j < a[i].length; j++) {
                        sheet.addCell(new jxl.write.Label(j, i, a[i][j]));
                    }
                }
                workbook.write();
                workbook.close();
                JOptionPane.showMessageDialog(null, "Reporte generado!");
            } else {
                JOptionPane.showMessageDialog(null, "Nombre inválido");
            }

        } catch (IOException ex) {
            Logger.getLogger(Consulta_Centrodetrabajo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (WriteException ex) {
            Logger.getLogger(Consulta_Centrodetrabajo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    void setVisible(boolean b, int i) {

    }

    void setVisible(Alumno c) {
        setVisible(true);
        this.Tabla.setValueAt(c.getMatricula(), 0, 0);
        this.Tabla.setValueAt(c.getNombreAlumno(), 0, 1);
        this.Tabla.setValueAt(c.getPaternoAlumno(), 0, 2);
        this.Tabla.setValueAt(c.getMaternoAlumno(), 0, 3);
        this.Tabla.setValueAt(c.getFechaNacimiento(), 0, 4);
        this.Tabla.setValueAt(c.getCalle(), 0, 5);
        this.Tabla.setValueAt(c.getColonia(), 0, 6);
        this.Tabla.setValueAt(c.getNumero(), 0, 7);
        this.Tabla.setValueAt(c.getCodigoPostal(), 0, 8);
        this.Tabla.setValueAt(c.getSexo(), 0, 9);
        this.Tabla.setValueAt(c.getEmail(), 0, 10);
        this.Tabla.setValueAt(c.getCarrera().getIdCarrera(), 0, 11);
        String[][] datos2 = new String[2][12];
        datos2[0][0] = "Matricula";
        datos2[0][1] = "Nombre";
        datos2[0][2] = "A. Paterno";
        datos2[0][3] = "A. Materno";
        datos2[0][4] = "Fecha Nac.";
        datos2[0][5] = "Calle";
        datos2[0][6] = "Colonia";
        datos2[0][7] = "Numero";
        datos2[0][8] = "CP";
        datos2[0][9] = "Sexo";
        datos2[0][10] = "e-mail";
        datos2[0][11] = "id de Carrera";
        datos2[1][0] = String.valueOf(c.getMatricula());
        datos2[1][1] = String.valueOf(c.getNombreAlumno());
        datos2[1][2] = String.valueOf(c.getPaternoAlumno());
        datos2[1][3] = String.valueOf(c.getMaternoAlumno());
        datos2[1][4] = String.valueOf(c.getFechaNacimiento());
        datos2[1][5] = String.valueOf(c.getCalle());
        datos2[1][6] = String.valueOf(c.getColonia());
        datos2[1][7] = String.valueOf(c.getNumero());
        datos2[1][8] = String.valueOf(c.getCodigoPostal());
        datos2[1][9] = String.valueOf(c.getSexo());
        datos2[1][10] = String.valueOf(c.getEmail());
        datos2[1][11] = String.valueOf(c.getCarrera().getIdCarrera());
        datos = datos2;

    }

    void setVisible(boolean b, DefaultListModel dl) {
        setVisible(true);
        System.out.println(dl.size());
        Object[][] filas = new Object[dl.size()][12];
        String[][] datos2 = new String[dl.size() + 1][12];
        datos2[0][0] = "Matricula";
        datos2[0][1] = "Nombre";
        datos2[0][2] = "A. Paterno";
        datos2[0][3] = "A. Materno";
        datos2[0][4] = "Fecha Nac.";
        datos2[0][5] = "Calle";
        datos2[0][6] = "Colonia";
        datos2[0][7] = "Numero";
        datos2[0][8] = "CP";
        datos2[0][9] = "Sexo";
        datos2[0][10] = "e-mail";
        datos2[0][11] = "id de Carrera";
        for (int i = 0; i < dl.size(); i++) {
            Alumno a = (Alumno) dl.get(i); //ASI SE RECIBE UNA LISTA
            filas[i][0] = a.getMatricula();
            filas[i][1] = a.getNombreAlumno();
            filas[i][2] = a.getPaternoAlumno();
            filas[i][3] = a.getMaternoAlumno();
            filas[i][4] = a.getFechaNacimiento();
            filas[i][5] = a.getCalle();
            filas[i][6] = a.getColonia();
            filas[i][7] = a.getNumero();
            filas[i][8] = a.getCodigoPostal();
            filas[i][9] = a.getSexo();
            filas[i][10] = a.getEmail();
            filas[i][11] = a.getCarrera().getIdCarrera();
            datos2[i+1][0] = String.valueOf(a.getMatricula());
            datos2[i+1][1] = String.valueOf(a.getNombreAlumno());
            datos2[i+1][2] = String.valueOf(a.getPaternoAlumno());
            datos2[i+1][3] = String.valueOf(a.getMaternoAlumno());
            datos2[i+1][4] = String.valueOf(a.getFechaNacimiento());
            datos2[i+1][5] = String.valueOf(a.getCalle());
            datos2[i+1][6] = String.valueOf(a.getColonia());
            datos2[i+1][7] = String.valueOf(a.getNumero());
            datos2[i+1][8] = String.valueOf(a.getCodigoPostal());
            datos2[i+1][9] = String.valueOf(a.getSexo());
            datos2[i+1][10] = String.valueOf(a.getEmail());
            datos2[i+1][11] = String.valueOf(a.getCarrera().getIdCarrera());
        }
        datos=datos2;
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
                filas,
                new String[]{
                    "Matriculo", "Nombre", "A. Paterno", "A. Materno", "Fecha Nac.", "Calle", "Colonia", "Numero", "CP", "Sexo", "e-mail", "id de Carrera"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

        });
        jScrollPane2.setViewportView(Tabla);
        jScrollPane2.setPreferredSize(new Dimension(3, 0));
        Tabla.setSize(200, 200);

    }

}
