/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Interfaces.AlumnoInt;
import Interfaces.CalificacionesInt;
import Interfaces.ExamenInt;
import Modelo.Alumno;
import Modelo.Calificaciones;
import Modelo.Examen;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.transaction.HeuristicMixedException;
import javax.transaction.HeuristicRollbackException;
import javax.transaction.RollbackException;
import javax.transaction.SystemException;

/**
 *
 * @author sam-y
 */
public class Formulario_Calificaciones_Alta extends javax.swing.JInternalFrame {

    int banderaCambio = 0;
    int idCambio = 0;

    /**
     * Creates new form Formulario_Calificaciones_Alta
     */
    public Formulario_Calificaciones_Alta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        puntaje = new javax.swing.JTextField();
        idExamen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idAlumno = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(162, 177, 192));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nueva Calificación");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Puntaje :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("id de Examen");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Matricula Alumno :");

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(puntaje))
                        .addComponent(jLabel4)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(idExamen))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(puntaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idExamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        this.puntaje.setText("");
        this.idAlumno.setText("");
        this.idExamen.setText("");
        this.jButton4.setText("Aceptar");
        banderaCambio = 0;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            AlumnoInt alumnoController = (AlumnoInt) Naming.lookup("rmi://localhost/alumnoController");
            ExamenInt examenController = (ExamenInt) Naming.lookup("rmi://localhost/examenController");
            CalificacionesInt calificacionesController = (CalificacionesInt) Naming.lookup("rmi://localhost/calificacionesController");
            if (this.puntaje.getText().length() > 0 && this.idAlumno.getText().length() > 0 && this.idExamen.getText().length() > 0) {
                if (this.puntaje.getText().matches("^(([0-9]+)(\\.[0-9]+)?)")) {
                    Examen e = examenController.selectoneExamen(Integer.valueOf(this.idExamen.getText()));
                    Alumno a = alumnoController.selectoneAlumno(Long.valueOf(this.idAlumno.getText()));
                    if (e != null) {
                        if (a != null) {
                            if (banderaCambio == 1) {
                                Calificaciones calificacion = new Calificaciones(idCambio, a, e, Double.valueOf(this.puntaje.getText()));
                                calificacionesController.updateCalificaciones(calificacion);
                                JOptionPane.showMessageDialog(null, "Modificacion exitosa");
                            } else {
                                DefaultListModel dl = calificacionesController.selectallCalificaciones();
                                Calificaciones c = (Calificaciones) dl.get(dl.size() - 1);
                                Calificaciones calificacion = new Calificaciones(c.getIdCalificaciones() + 1, a, e, Double.valueOf(this.puntaje.getText()));
                                calificacionesController.insertCalificaciones(calificacion);
                                JOptionPane.showMessageDialog(null, "Registro exitoso");
                            }
                            this.setVisible(false);
                            this.puntaje.setText("");
                            this.idAlumno.setText("");
                            this.idExamen.setText("");
                            this.jButton4.setText("Aceptar");
                            banderaCambio = 0;
                        } else {
                            JOptionPane.showMessageDialog(null, "id de alumno inválido");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "id de examen inválido");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "formato de puntaje incorrecto");
                }
            } else {
                JOptionPane.showMessageDialog(null, "completa todos los campos");
            }
        } catch (NotBoundException | MalformedURLException | RemoteException | SecurityException ex) {
            Logger.getLogger(Formulario_Centrodetrabajo_Alta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HeuristicMixedException ex) {
            Logger.getLogger(Formulario_Calificaciones_Alta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RollbackException ex) {
            Logger.getLogger(Formulario_Calificaciones_Alta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HeuristicRollbackException ex) {
            Logger.getLogger(Formulario_Calificaciones_Alta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SystemException ex) {
            Logger.getLogger(Formulario_Calificaciones_Alta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idAlumno;
    private javax.swing.JTextField idExamen;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField puntaje;
    // End of variables declaration//GEN-END:variables

    void setVisible(boolean b, int i) throws NotBoundException {
        try {
            setVisible(true);
            String stringInput = JOptionPane.showInputDialog("Id de la Calificacion a modificar");
            if (stringInput != null) {
                int id = Integer.valueOf(stringInput);
                CalificacionesInt calificacionesController = (CalificacionesInt) Naming.lookup("rmi://localhost/calificacionesController");
                Calificaciones c = calificacionesController.selectoneCalificaciones(id);
                if (c != null) {
                    this.puntaje.setText(String.valueOf(c.getPuntuaje()));
                    this.idAlumno.setText(String.valueOf(c.getAlumno().getMatricula()));
                    this.idExamen.setText(String.valueOf(c.getExamen().getIdExamen()));
                    this.jButton3.setText("Cambiar");
                    banderaCambio = 1;
                    idCambio = id;
                } else {
                    JOptionPane.showMessageDialog(null, "Id inválido");
                    this.setVisible(false);
                    this.puntaje.setText("");
                    this.idAlumno.setText("");
                    this.idExamen.setText("");
                    this.jButton4.setText("Aceptar");
                    banderaCambio = 0;
                }
            } else {
                this.setVisible(false);
                this.puntaje.setText("");
                this.idAlumno.setText("");
                this.idExamen.setText("");
                this.jButton4.setText("Aceptar");
                banderaCambio = 0;
            }

        } catch (MalformedURLException | RemoteException ex) {
            Logger.getLogger(Formulario_Centrodetrabajo_Alta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
