package modelos;
// Generated Dec 2, 2018 9:45:08 PM by Hibernate Tools 4.3.1

/**
 * Employees generated by hbm2java
 */
public class Employees  implements java.io.Serializable {


     private Integer employeeId;
     private String password;
     private String privilege;
     private String lastName;
     private String firstName;
     private String title;
     private String titleOfCourtesy;
     private String birthDate;
     private String hireDate;
     private String address;
     private String city;
     private String region;
     private String postalCode;
     private String country;
     private String homePhone;
     private String phoneExtension;
     private String photo;
     private String notes;
     private String reportsTo;

    public Employees() {
    }

    public Employees(String password, String privilege, String lastName, String firstName, String title, String titleOfCourtesy, String birthDate, String hireDate, String address, String city, String region, String postalCode, String country, String homePhone, String phoneExtension, String photo, String notes, String reportsTo) {
       this.password = password;
       this.privilege = privilege;
       this.lastName = lastName;
       this.firstName = firstName;
       this.title = title;
       this.titleOfCourtesy = titleOfCourtesy;
       this.birthDate = birthDate;
       this.hireDate = hireDate;
       this.address = address;
       this.city = city;
       this.region = region;
       this.postalCode = postalCode;
       this.country = country;
       this.homePhone = homePhone;
       this.phoneExtension = phoneExtension;
       this.photo = photo;
       this.notes = notes;
       this.reportsTo = reportsTo;
    }
   
    public Integer getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getTitleOfCourtesy() {
        return this.titleOfCourtesy;
    }
    
    public void setTitleOfCourtesy(String titleOfCourtesy) {
        this.titleOfCourtesy = titleOfCourtesy;
    }
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }
    public String getHireDate() {
        return this.hireDate;
    }
    
    public void setHireDate(String hireDate) {
        this.hireDate = hireDate;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }
    public String getPhoneExtension() {
        return this.phoneExtension;
    }
    
    public void setPhoneExtension(String phoneExtension) {
        this.phoneExtension = phoneExtension;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getReportsTo() {
        return this.reportsTo;
    }
    
    public void setReportsTo(String reportsTo) {
        this.reportsTo = reportsTo;
    }

    public String toString(){
        return this.employeeId+";"+this.password+";"+this.privilege+";"+this.lastName+";"+this.firstName+";"+this.title+";"+this.titleOfCourtesy+";"+this.birthDate+";"+this.hireDate+";"+this.address+";"+this.city+";"+this.region+";"+this.postalCode+";"+this.country+";"+this.homePhone+";"+this.phoneExtension+";"+this.photo+";"+this.notes+";"+this.reportsTo;
    }

}


