package modelos;
// Generated Dec 2, 2018 9:45:08 PM by Hibernate Tools 4.3.1



/**
 * Orderdetails generated by hbm2java
 */
public class Orderdetails  implements java.io.Serializable {


     private Integer orderDetailsId;
     private Orders orders;
     private Products products;
     private Long unitPrice;
     private Integer quantity;
     private Double discount;

    public Orderdetails() {
    }

    public Orderdetails(Orders orders, Products products, Long unitPrice, Integer quantity, Double discount) {
       this.orders = orders;
       this.products = products;
       this.unitPrice = unitPrice;
       this.quantity = quantity;
       this.discount = discount;
    }
   
    public Integer getOrderDetailsId() {
        return this.orderDetailsId;
    }
    
    public void setOrderDetailsId(Integer orderDetailsId) {
        this.orderDetailsId = orderDetailsId;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }
    public Long getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Long unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Double discount) {
        this.discount = discount;
    }




}


