package modelos;
// Generated Dec 2, 2018 9:45:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer orderId;
     private Customers customers;
     private Employees employees;
     private String orderDate;
     private String requiredDate;
     private String shippedDate;
     private Integer shipVia;
     private Long freight;
     private String shipName;
     private String shipAddress;
     private String shipCity;
     private String shipRegion;
     private String shipPostalCode;
     private String shipCountry;
     private Set orderdetailses = new HashSet(0);

    public Orders() {
    }

    public Orders(Customers customers, Employees employees, String orderDate, String requiredDate, String shippedDate, Integer shipVia, Long freight, String shipName, String shipAddress, String shipCity, String shipRegion, String shipPostalCode, String shipCountry, Set orderdetailses) {
       this.customers = customers;
       this.employees = employees;
       this.orderDate = orderDate;
       this.requiredDate = requiredDate;
       this.shippedDate = shippedDate;
       this.shipVia = shipVia;
       this.freight = freight;
       this.shipName = shipName;
       this.shipAddress = shipAddress;
       this.shipCity = shipCity;
       this.shipRegion = shipRegion;
       this.shipPostalCode = shipPostalCode;
       this.shipCountry = shipCountry;
       this.orderdetailses = orderdetailses;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public String getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(String orderDate) {
        this.orderDate = orderDate;
    }
    public String getRequiredDate() {
        return this.requiredDate;
    }
    
    public void setRequiredDate(String requiredDate) {
        this.requiredDate = requiredDate;
    }
    public String getShippedDate() {
        return this.shippedDate;
    }
    
    public void setShippedDate(String shippedDate) {
        this.shippedDate = shippedDate;
    }
    public Integer getShipVia() {
        return this.shipVia;
    }
    
    public void setShipVia(Integer shipVia) {
        this.shipVia = shipVia;
    }
    public Long getFreight() {
        return this.freight;
    }
    
    public void setFreight(Long freight) {
        this.freight = freight;
    }
    public String getShipName() {
        return this.shipName;
    }
    
    public void setShipName(String shipName) {
        this.shipName = shipName;
    }
    public String getShipAddress() {
        return this.shipAddress;
    }
    
    public void setShipAddress(String shipAddress) {
        this.shipAddress = shipAddress;
    }
    public String getShipCity() {
        return this.shipCity;
    }
    
    public void setShipCity(String shipCity) {
        this.shipCity = shipCity;
    }
    public String getShipRegion() {
        return this.shipRegion;
    }
    
    public void setShipRegion(String shipRegion) {
        this.shipRegion = shipRegion;
    }
    public String getShipPostalCode() {
        return this.shipPostalCode;
    }
    
    public void setShipPostalCode(String shipPostalCode) {
        this.shipPostalCode = shipPostalCode;
    }
    public String getShipCountry() {
        return this.shipCountry;
    }
    
    public void setShipCountry(String shipCountry) {
        this.shipCountry = shipCountry;
    }
    public Set getOrderdetailses() {
        return this.orderdetailses;
    }
    
    public void setOrderdetailses(Set orderdetailses) {
        this.orderdetailses = orderdetailses;
    }




}


