package modelos;
// Generated Dec 2, 2018 9:45:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private Integer productId;
     private Categories categories;
     private Suppliers suppliers;
     private String productName;
     private String quantityPerUnity;
     private Long unitPrice;
     private Integer unitInStock;
     private Integer unitsOnOrder;
     private Integer reorderLevel;
     private Integer discontinued;
     private Set orderdetailses = new HashSet(0);

    public Products() {
    }

    public Products(Categories categories, Suppliers suppliers, String productName, String quantityPerUnity, Long unitPrice, Integer unitInStock, Integer unitsOnOrder, Integer reorderLevel, Integer discontinued, Set orderdetailses) {
       this.categories = categories;
       this.suppliers = suppliers;
       this.productName = productName;
       this.quantityPerUnity = quantityPerUnity;
       this.unitPrice = unitPrice;
       this.unitInStock = unitInStock;
       this.unitsOnOrder = unitsOnOrder;
       this.reorderLevel = reorderLevel;
       this.discontinued = discontinued;
       this.orderdetailses = orderdetailses;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public String getQuantityPerUnity() {
        return this.quantityPerUnity;
    }
    
    public void setQuantityPerUnity(String quantityPerUnity) {
        this.quantityPerUnity = quantityPerUnity;
    }
    public Long getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Long unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Integer getUnitInStock() {
        return this.unitInStock;
    }
    
    public void setUnitInStock(Integer unitInStock) {
        this.unitInStock = unitInStock;
    }
    public Integer getUnitsOnOrder() {
        return this.unitsOnOrder;
    }
    
    public void setUnitsOnOrder(Integer unitsOnOrder) {
        this.unitsOnOrder = unitsOnOrder;
    }
    public Integer getReorderLevel() {
        return this.reorderLevel;
    }
    
    public void setReorderLevel(Integer reorderLevel) {
        this.reorderLevel = reorderLevel;
    }
    public Integer getDiscontinued() {
        return this.discontinued;
    }
    
    public void setDiscontinued(Integer discontinued) {
        this.discontinued = discontinued;
    }
    public Set getOrderdetailses() {
        return this.orderdetailses;
    }
    
    public void setOrderdetailses(Set orderdetailses) {
        this.orderdetailses = orderdetailses;
    }




}


